### ISSUE TITLE
Accessibility: Glassdoor Logo and Rating

### ISSUE THREAD

**Issue by michaelspellacy** [radancyco/tb-ajd-template#15]
@Brockenstein  Would it be possible to use an inline image for the Glassdoor logo/rating instead of a CSS background image? This is important information that is being excluded from individuals who may be using Windows 7/High Contrast Mode. While this is a MS issue, we need to ensure it is addressed anyway. Thanks!

**Comment by Brockenstein** [comment]
@michaelspellacy  I suppose so, the only reason I think I did background image was because before it was styles we had to manually update from time to time and best to do it in once place, how it is using an api to be up to day. The only other thing is in the case of needing to switch to thee different layout at a different size but that could be done with the picture tag.

I will leave this open for other input. If no one else has any concerns I can change it.

**Comment by michaelspellacy** [comment]
Any update?

**Comment by Brockenstein** [comment]
This is in progress. We have to update the Checker so that it make sure that the DEV updates the image src. Once that is updated we should be able to push this change out.

**Comment by Brockenstein** [comment]
I have set aside time for this next week to finish up.

**Comment by dchacon1** [comment]
@michaelspellacy This issue has finally been addressed. It will be published when we roll out v2 of the AJD. You can reference https://francis.runmytests.com/job/united-states/account-director-fortune-50-client/1554/15243862
CC @Brockenstein

**Comment by michaelspellacy** [comment]
Thanks, gents!
