### ISSUE TITLE
Accessibility: Change Success Profile <ul> to <ol>

### ISSUE THREAD

**Issue by michaelspellacy** [radancyco/tb-ajd-template#19]
See grab. https://www.screencast.com/t/1vH4dmXrX 

Sequential or numbered items should really be in a numbered list. That and one less thing for third-party tools and auditing teams to cite issues on. Please change when you have the time. Thanks!

**Comment by Brockenstein** [comment]
@michaelspellacy I understand what you are saying but I am not sure I see how it applied to the trait circle. The idea with that circle is that they are all equal, no one ranked higher than the other. All skills are important, so wouldn't an unordered list match that logic of the content?

**Comment by dchacon1** [comment]
@michaelspellacy @Brockenstein I am a little unsure of this too. When I look at the page I never thought it was supposed to be a list of "numbered items."  That was because the page was designed with the idea that these skills are all of equal importance. 

With that being said though, I am not under the impression that the ONLY reason to use OL is because the items HAVE to be in a certain order or because one item is more important than the other. 
If we are trying to indicate the the user HOW MANY skills there are in the list then I think a numbered list would be appropriate and we could use OL and make sure that those numbers are also added for visual users benefit, but if not I don't see how making the list an OL would be of benefit to non-visual users.

**Comment by Brockenstein** [comment]
@michaelspellacy  @dchacon1  looking at that screencast again it looks like @michaelspellacy is referring to the bar chart and not the trait circle.
Which again, why would be do an OL list? he skills are never listed from most important to least important. They each have a seperate number inside of them.
Also, in order to change it to an OL we would need to hide the number. Which seems like it defeats the purpose there too.

**Comment by jkmahoney** [comment]
Are we only referring to the skills chart (the bar graph version) or also the circle traits here?

I feel that they are two different things, but creative is using them to express the same information just in a different layout/view.

The question I would raise is if the list of skills whether in the skill graph or the trait circle are actually listed items or numbered items? Personally, I don't see them as numbered items since several can have the same priority weight, for instance, two or three of them having tens or sevens. They are also not listed in any particular order of priority since there could be a ten as the first option, a five as the second, and then an eight as the third. If this was truly a numbered list it would be in sequential order, correct?

I think that we have used the UL in this case because it's just a "container/holder" for the information we are trying to convey for styling purposes, the same way we could just as easily use div tags, but since we are listing the items out we put them in a UL.

**Comment by michaelspellacy** [comment]
My bad. I meant bar chart. I really don't have an issue with us making this a numbered list instead of an unordered one. Semantically speaking, it *could* be seen that way, so I think it is fine to put through. Also, in dealing with third-party auditors, some have a tendency to blindly insist on meeting automated results, so I'm seeking to quell those moments as well. :-)

**Comment by michaelspellacy** [comment]
One last thing. When it come to litigious behavior, there are many who hold the results of these scans against our clients and use as leverage when they cite issues. Sad, but this is the world we live in. Wave, and the people who make it, are highly reputable in the a11y space, so I almost always trust their results. Even in this case, it could be argued that the bar chart, along with the list below it, could be an ordered list, which is why I have no issue with changing them and erring on the side of caution. :-)

**Comment by Brockenstein** [comment]
@michaelspellacy I thought the semantics was Unordered lists are used when the order of the items is not relevant and Ordered lists are used for sequential information. Is that not right?

Maybe for the bar chart, we shouldn't be using a UL/OL at all? Since really the reason it is being used is to group the containing HTML together it should just be a DIV?

**Comment by michaelspellacy** [comment]
@Brockenstein Yes, this is correct. I would say, more times than not, that creative (and many clients) are choosing what gets listed first based on a preference or priority, which is why I see no harm in conveying this as a  numbered list.  I would rather see some semblance of something semantically useful with an ordered list, than nothing at all, with divs. :-)

**Comment by Brockenstein** [comment]
@michaelspellacy please note that changing this from an unordered list to an ordered list will not remove the amount of items that WAVE will flag.

Please seen screenshot where I did a test and now WAVE flags this as an ordered list instead of an unordered list. https://www.screencast.com/t/9kn2aIX9xcDw 

The goal of this requested changed was to make it so there is "one less thing for third-party tools and auditing teams to cite issues on" however making this change from OL to UL makes no difference towards that goal. If you want to get rid of this as being flagged by WAVE then maybe consider using DIVs. However you stated you "would rather see some semblance of something semantically useful".

At this point I feel like we are at an impasse.

**Comment by michaelspellacy** [comment]
@Brockenstein  Okay, let's keep as an ul...for now. We'll simply mark it a a false positive and change to ol on a case by case basis.
