### ISSUE TITLE
Update AJD Nav

### ISSUE THREAD

**Issue by michaelspellacy** [radancyco/tb-ajd-template#20]
Can we make a slight improvement to the AJD navigation and make it nav instead of a div? 

<nav class="ajd_navigation" aria-label="job details"> ... </nav>

You can change label value if you like. The purpose is to differentiate it from main navigation. AT's will read out first link it lands on, like this: "Overview job details", etc. 

Thanks!

**Comment by Brockenstein** [comment]
@michaelspellacy should these also become buttons instead of links?

**Comment by michaelspellacy** [comment]
@Brockenstein No, even tho we are suppressing normal link behavior here to jump/scroll down to another  portion of the page, we a) still want those to be read out as links to AT and b) want them to still work if there is an issue with script on the page.

**Comment by Brockenstein** [comment]
Thanks
I have set aside time next week to tackle this issue

**Comment by dchacon1** [comment]
@michaelspellacy This issue has finally been addressed. It will be published when we roll out v2 of the AJD. You can reference https://francis.runmytests.com/job/united-states/account-director-fortune-50-client/1554/15243862

In addition I added aria-label so that it can be distinguished from and existing navigation.
CC @Brockenstein
